services:
  - type: web
    name: fikiri-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    plan: starter
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///data/fikiri.db
      - key: REDIS_URL
        value: redis://localhost:6379
      - key: SENTRY_DSN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        value: https://fikirisolutions.onrender.com/api/oauth/gmail/callback
      - key: FERNET_KEY
        generateValue: true
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true
    branch: main
    
  - type: web
    name: fikiri-backend-staging
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    plan: starter
    envVars:
      - key: FLASK_ENV
        value: staging
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///data/fikiri_staging.db
    healthCheckPath: /api/health
    autoDeploy: true
    branch: develop